export const serviceCategories = [
  {
    id: "individual",
    title: "Individual Services",
    subtitle: "Precision Modules",
    description: "Engineer exactly what you need to elevate your brand",
    detailedDescription:
      "Choose from our curated selection of premium design, development, and strategy services to build your perfect solution",
    priceRange: "$197 - $2,497",
    services: 16,
    color: "emerald",
    gradient: "from-emerald-500/30 to-teal-500/20",
    glowColor: "emerald-500",
    icon: "◆",
    highlights: [
      "16 Premium Services",
      "Mix & Match Approach",
      "No Long-Term Contracts",
    ],
    targetSection: "individual-services",
    ctaText: "Browse All Services",
  },
  {
    id: "memberships",
    title: "Creative Memberships",
    subtitle: "Monthly Value Bundles",
    description: "All-access passes to our premium services & community",
    detailedDescription:
      "Monthly memberships that bundle our most popular services with exclusive community access and significant savings",
    priceRange: "$10 - $50/mo",
    services: 3,
    color: "purple",
    gradient: "from-purple-500/30 to-pink-500/20",
    glowColor: "purple-500",
    icon: "♦",
    highlights: [
      "3 Membership Tiers",
      "Save up to $220/mo",
      "VIP Community Access",
    ],
    targetSection: "community-memberships",
    ctaText: "View Memberships",
  },
  {
    id: "packages",
    title: "Agency Packages",
    subtitle: "Complete Brand Transformation",
    description: "Full-service brand elevation from vision to reality",
    detailedDescription:
      "Comprehensive packages that transform your entire brand presence with premium design, development, and strategic positioning",
    priceRange: "$5K - $25K",
    services: 3,
    color: "blue",
    gradient: "from-blue-500/30 to-cyan-500/20",
    glowColor: "blue-500",
    icon: "⬡",
    highlights: [
      "Complete Brand Overhaul",
      "Save up to $12.2K",
      "Full-Stack Development",
    ],
    targetSection: "agency-packages",
    ctaText: "Explore Packages",
  },
];

export const individualServices = [
  {
    name: "Brand Vision Audit",
    price: "$297",
    category: "Strategy",
    description:
      "Deep-dive analysis of your brand's digital presence potential & competitive positioning",
    gradient: "from-purple-500/20 to-indigo-600/10",
    borderColor: "border-purple-300/40 hover:border-purple-400/60",
    glowColor: "purple-500",
    categoryColor: "bg-purple-100 text-purple-700",
  },
  {
    name: "Premium Logo Design",
    price: "$597",
    category: "Design",
    description:
      "Sophisticated logo system with brand story integration & scalable design assets",
    gradient: "from-indigo-500/20 to-violet-600/10",
    borderColor: "border-indigo-300/40 hover:border-indigo-400/60",
    glowColor: "indigo-500",
    categoryColor: "bg-indigo-100 text-indigo-700",
  },
  {
    name: "Business Card Design",
    price: "$197",
    category: "Design",
    description:
      "Modern business card design with premium finishes & brand consistency",
    gradient: "from-indigo-500/20 to-violet-600/10",
    borderColor: "border-indigo-300/40 hover:border-indigo-400/60",
    glowColor: "indigo-500",
    categoryColor: "bg-indigo-100 text-indigo-700",
  },
  {
    name: "Social Media Kit",
    price: "$397",
    category: "Design",
    description:
      "Complete social media template system with story templates & post designs",
    gradient: "from-violet-500/20 to-pink-600/10",
    borderColor: "border-violet-300/40 hover:border-violet-400/60",
    glowColor: "violet-500",
    categoryColor: "bg-violet-100 text-violet-700",
  },
  {
    name: "Future-Ready Landing Page",
    price: "$997",
    category: "Web Design",
    description:
      "Next-generation single page with 3D elements & conversion-optimized UX",
    gradient: "from-pink-500/20 to-rose-600/10",
    borderColor: "border-pink-300/40 hover:border-pink-400/60",
    glowColor: "pink-500",
    categoryColor: "bg-pink-100 text-pink-700",
  },
  {
    name: "Multi-Page Website",
    price: "$1,497",
    category: "Web Design",
    description:
      "5-7 page responsive website with CMS integration & mobile optimization",
    gradient: "from-rose-500/20 to-red-600/10",
    borderColor: "border-rose-300/40 hover:border-rose-400/60",
    glowColor: "rose-500",
    categoryColor: "bg-rose-100 text-rose-700",
  },
  {
    name: "E-commerce Store",
    price: "$1,897",
    category: "Web Design",
    description:
      "Full e-commerce solution with payment integration & inventory management",
    gradient: "from-red-500/20 to-orange-600/10",
    borderColor: "border-red-300/40 hover:border-red-400/60",
    glowColor: "red-500",
    categoryColor: "bg-red-100 text-red-700",
  },
  {
    name: "Hero Animation Sequence",
    price: "$1,297",
    category: "Animation",
    description:
      "Custom Spline 3D animation that elevates your brand narrative & engagement",
    gradient: "from-orange-500/20 to-yellow-600/10",
    borderColor: "border-orange-300/40 hover:border-orange-400/60",
    glowColor: "orange-500",
    categoryColor: "bg-orange-100 text-orange-700",
  },
  {
    name: "Micro-Interactions",
    price: "$497",
    category: "Animation",
    description:
      "Subtle animations for buttons, forms & page transitions that enhance UX",
    gradient: "from-yellow-500/20 to-lime-600/10",
    borderColor: "border-yellow-300/40 hover:border-yellow-400/60",
    glowColor: "yellow-500",
    categoryColor: "bg-yellow-100 text-yellow-700",
  },
  {
    name: "Brand Video Animation",
    price: "$897",
    category: "Animation",
    description:
      "30-60 second brand story animation for social media & website use",
    gradient: "from-lime-500/20 to-green-600/10",
    borderColor: "border-lime-300/40 hover:border-lime-400/60",
    glowColor: "lime-500",
    categoryColor: "bg-lime-100 text-lime-700",
  },
  {
    name: "Visionary Brand Strategy",
    price: "$1,197",
    category: "Strategy",
    description:
      "Complete brand positioning with future-focused narrative & market differentiation",
    gradient: "from-green-500/20 to-emerald-600/10",
    borderColor: "border-green-300/40 hover:border-green-400/60",
    glowColor: "green-500",
    categoryColor: "bg-green-100 text-green-700",
  },
  {
    name: "Brand Guidelines Document",
    price: "$597",
    category: "Strategy",
    description:
      "Comprehensive brand book with usage guidelines & design standards",
    gradient: "from-emerald-500/20 to-teal-600/10",
    borderColor: "border-emerald-300/40 hover:border-emerald-400/60",
    glowColor: "emerald-500",
    categoryColor: "bg-emerald-100 text-emerald-700",
  },
  {
    name: "Reality Design Experience",
    price: "$2,497",
    category: "Experimental",
    description:
      "Immersive digital experience that transforms how audiences interact with your brand",
    gradient: "from-teal-500/20 to-cyan-600/10",
    borderColor: "border-teal-300/40 hover:border-teal-400/60",
    glowColor: "teal-500",
    categoryColor: "bg-teal-100 text-teal-700",
  },
  {
    name: "Interactive Prototype",
    price: "$797",
    category: "Experimental",
    description:
      "Clickable prototype with advanced interactions & user flow testing",
    gradient: "from-cyan-500/20 to-blue-600/10",
    borderColor: "border-cyan-300/40 hover:border-cyan-400/60",
    glowColor: "cyan-500",
    categoryColor: "bg-cyan-100 text-cyan-700",
  },
  {
    name: "Strategic Consultation",
    price: "$297",
    category: "Consulting",
    description:
      "90-min deep-dive on brand evolution & digital transformation strategy",
    gradient: "from-blue-500/20 to-indigo-600/10",
    borderColor: "border-blue-300/40 hover:border-blue-400/60",
    glowColor: "blue-500",
    categoryColor: "bg-blue-100 text-blue-700",
  },
  {
    name: "Design Review & Feedback",
    price: "$197",
    category: "Consulting",
    description:
      "Professional design critique with actionable improvement recommendations",
    gradient: "from-indigo-500/20 to-purple-600/10",
    borderColor: "border-indigo-300/40 hover:border-indigo-400/60",
    glowColor: "indigo-500",
    categoryColor: "bg-indigo-100 text-indigo-700",
  },
];

export const communityMemberships = [
  {
    tier: "DREAMER",
    price: "$10",
    period: "/mo",
    savings: "Save $65/mo",
    includes: [
      "Monthly Article ($25 value)",
      "Guided Meditation ($15 value)",
      "Behind-the-Scenes Video ($35 value)",
      "Discord Community Access ($10 value)",
      "10% Merch Discount",
    ],
    level: "01",
    gradient: "from-purple-500/15 to-pink-500/10",
    glowColor: "purple-500",
    narrative:
      "Every dreamer needs the foundation to manifest their vision into reality.",
  },
  {
    tier: "CREATOR",
    price: "$25",
    period: "/mo",
    savings: "Save $160/mo",
    includes: [
      "Everything in Dreamer ($85 value)",
      "Live Workshop ($50 value)",
      "Tutorial Creation ($75 value)",
      "Creator Discord Channel",
      "20% Merch + 10% Agency Discount",
    ],
    level: "02",
    gradient: "from-purple-500/20 to-blue-500/15",
    glowColor: "blue-500",
    narrative:
      "Creators transform inspiration into experiences that touch souls across dimensions.",
    featured: true,
  },
  {
    tier: "VISIONARY",
    price: "$50",
    period: "/mo",
    savings: "Save $220/mo",
    includes: [
      "Everything in Creator ($210 value)",
      "Quarterly Coaching Call ($150 value)",
      "Early Content Access ($20 value)",
      "VIP Discord + Monthly AMAs",
      "Annual Limited-Edition Merch",
      "20% Agency Discount",
    ],
    level: "03",
    gradient: "from-purple-500/25 to-indigo-500/20",
    glowColor: "indigo-500",
    narrative:
      "Visionaries see beyond the veil and architect the impossible into existence.",
  },
];

export const agencyPackages = [
  {
    package: "VISION STARTER",
    price: "$5,000",
    savings: "Save $2,300",
    includes: [
      "Website 3-5 pages ($2,500 value)",
      "Hero Animation ($1,200 value)",
      "Logo Package ($800 value)",
      "Messaging Deck ($800 value)",
      "Figma Files + CMS Training",
      "Vercel Deployment",
    ],
    level: "01",
    gradient: "from-blue-500/15 to-cyan-500/10",
    glowColor: "blue-500",
    narrative:
      "Every vision needs a foundation to manifest into digital reality.",
  },
  {
    package: "REALITY ARCHITECT",
    price: "$15,000",
    savings: "Save $7,400",
    includes: [
      "Everything in Vision Starter ($5,000 value)",
      "Expanded Website 7-10 pages ($4,500 value)",
      "2 Custom Animations ($4,000 value)",
      "Complete Brand Book ($2,500 value)",
      "Social Launch Kit ($600 value)",
      "Analytics Setup (GA4 + Hotjar)",
    ],
    level: "02",
    gradient: "from-blue-500/20 to-teal-500/15",
    glowColor: "teal-500",
    narrative:
      "Architects design the infrastructure where consciousness meets technology.",
  },
  {
    package: "COSMIC CREATOR",
    price: "$25,000",
    savings: "Save $12,200",
    includes: [
      "Everything in Reality Architect ($15,000 value)",
      "Narrative Strategy Guide ($1,800 value)",
      "Custom Music Track ($1,500 value)",
      "NFT Artwork ($2,000 value)",
      "Signature Animation ($3,500 value)",
      "30-Day VIP Support (2 sprints)",
    ],
    level: "03",
    gradient: "from-blue-500/25 to-indigo-500/20",
    glowColor: "indigo-500",
    narrative:
      "Cosmic creators transcend boundaries and architect impossible realities.",
  },
];
